### PR TITLE
Test enum methods

### PR DESCRIPTION
**Pull request by gitnyasha**
written tests for 6 of the enumerable methods with several inputs of the outcome

### CODE REVIEW

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @gitnyasha :handshake: 

### Good job so far on creating your test cases, :medal_sports:  you've used 'describe', 'it', and 'let' as it should :ok_hand:  there is one more thing to add to them and also a couple of missing methods to work on :construction_worker_man: :construction: 

## Project Specific

#### Test cases are missing

- [x] All methods implemented in the Enumerable project are tested. let's add test cases for all of the methods existing in your enumerable.rb, you've missed these ones:

- my_select
- my_map
- my_inject
- multiply_els
- sorted?
- inj_param

#### cover positive and negative scenarios

- [x] add negative test cases (use not_to) to all your test cases for example:

```
.
.
let(:array) { [1, 2, 5, 8, 7, 98, 4] }
.
.
  describe '#select' do
    #Positive test case example
    it 'Returns the filtered array if a block is given' do
      expect(array.select { |element| element > 1}).to eql([2, 5, 8, 7, 98, 4])
    end
    #Negative test case example
    it 'doesn\'t return the unfiltered array if a block is given' do
      expect(array.select { |element| element > 1}).not_to eql(array)
    end
  end
.
.
```
### That's it! :raised_hands: 

### Please :pray:  do the changes :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? let me know on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by gitnyasha** [comment]
> > ### Pull Request under the review by Maria Eugenia Queme P. (TSE)
> 
> ### Hello @gitnyasha 🤝
> ### Good job so far on creating your test cases, 🏅 you've used 'describe', 'it', and 'let' as it should 👌 there is one more thing to add to them and also a couple of missing methods to work on 👷 🚧
> ## Project Specific
> #### Test cases are missing
> * [ ]  All methods implemented in the Enumerable project are tested. let's add test cases for all of the methods existing in your enumerable.rb, you've missed these ones:
> * my_select
> * my_map
> * my_inject
> * multiply_els
> * sorted?
> * inj_param
> 
> #### cover positive and negative scenarios
> * [ ]  add negative test cases (use not_to) to all your test cases for example:
> 
> ```
> .
> .
> let(:array) { [1, 2, 5, 8, 7, 98, 4] }
> .
> .
>   describe '#select' do
>     #Positive test case example
>     it 'Returns the filtered array if a block is given' do
>       expect(array.select { |element| element > 1}).to eql([2, 5, 8, 7, 98, 4])
>     end
>     #Negative test case example
>     it 'doesn\'t return the unfiltered array if a block is given' do
>       expect(array.select { |element| element > 1}).not_to eql(array)
>     end
>   end
> .
> .
> ```
> 
> ### That's it! 🙌
> ### Please 🙏 do the changes 👨‍💻 and submit back for a code review when you are done 📝
> Happy coding! 🚀
> 
> Any questions? let me know on slack **@ Maru** 👩‍💻
> 
> PROJECT STATUS: REQUESTED CHANGES 🚦

I thought the instructions was any of the 6 enumerables

**Comment by euqueme** [comment]
> > > ### Pull Request under the review by Maria Eugenia Queme P. (TSE)
> > 
> > 
> > ### Hello @gitnyasha handshake
> > ### Good job so far on creating your test cases, medal_sports you've used 'describe', 'it', and 'let' as it should ok_hand there is one more thing to add to them and also a couple of missing methods to work on construction_worker_man construction
> > ## Project Specific
> > #### Test cases are missing
> > 
> > * [ ]   All methods implemented in the Enumerable project are tested. let's add test cases for all of the methods existing in your enumerable.rb, you've missed these ones:
> > * my_select
> > * my_map
> > * my_inject
> > * multiply_els
> > * sorted?
> > * inj_param
> > 
> > #### cover positive and negative scenarios
> > 
> > * [ ]   add negative test cases (use not_to) to all your test cases for example:
> > 
> > ```
> > .
> > .
> > let(:array) { [1, 2, 5, 8, 7, 98, 4] }
> > .
> > .
> >   describe '#select' do
> >     #Positive test case example
> >     it 'Returns the filtered array if a block is given' do
> >       expect(array.select { |element| element > 1}).to eql([2, 5, 8, 7, 98, 4])
> >     end
> >     #Negative test case example
> >     it 'doesn\'t return the unfiltered array if a block is given' do
> >       expect(array.select { |element| element > 1}).not_to eql(array)
> >     end
> >   end
> > .
> > .
> > ```
> > 
> > 
> > ### That's it! raised_hands
> > ### Please pray do the changes man_technologist and submit back for a code review when you are done memo
> > Happy coding! rocket
> > Any questions? let me know on slack **@ Maru** woman_technologist
> > PROJECT STATUS: REQUESTED CHANGES vertical_traffic_light
> 
> I thought the instructions was any of the 6 enumerables

- [ ] It is stated in the additional Microverse requirements in the [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)

image

**Comment by gitnyasha** [comment]
> > > > ### Pull Request under the review by Maria Eugenia Queme P. (TSE)
> > > 
> > > 
> > > ### Hello @gitnyasha handshake
> > > ### Good job so far on creating your test cases, medal_sports you've used 'describe', 'it', and 'let' as it should ok_hand there is one more thing to add to them and also a couple of missing methods to work on construction_worker_man construction
> > > ## Project Specific
> > > #### Test cases are missing
> > > 
> > > * [ ]    All methods implemented in the Enumerable project are tested. let's add test cases for all of the methods existing in your enumerable.rb, you've missed these ones:
> > > * my_select
> > > * my_map
> > > * my_inject
> > > * multiply_els
> > > * sorted?
> > > * inj_param
> > > 
> > > #### cover positive and negative scenarios
> > > 
> > > * [ ]    add negative test cases (use not_to) to all your test cases for example:
> > > 
> > > ```
> > > .
> > > .
> > > let(:array) { [1, 2, 5, 8, 7, 98, 4] }
> > > .
> > > .
> > >   describe '#select' do
> > >     #Positive test case example
> > >     it 'Returns the filtered array if a block is given' do
> > >       expect(array.select { |element| element > 1}).to eql([2, 5, 8, 7, 98, 4])
> > >     end
> > >     #Negative test case example
> > >     it 'doesn\'t return the unfiltered array if a block is given' do
> > >       expect(array.select { |element| element > 1}).not_to eql(array)
> > >     end
> > >   end
> > > .
> > > .
> > > ```
> > > 
> > > 
> > > ### That's it! raised_hands
> > > ### Please pray do the changes man_technologist and submit back for a code review when you are done memo
> > > Happy coding! rocket
> > > Any questions? let me know on slack **@ Maru** woman_technologist
> > > PROJECT STATUS: REQUESTED CHANGES vertical_traffic_light
> > 
> > 
> > I thought the instructions was any of the 6 enumerables
> 
> * [ ]  It is stated in the additional Microverse requirements in the [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)
> 
> image

ok

**Comment by gitnyasha** [comment]
> > > > ### Pull Request under the review by Maria Eugenia Queme P. (TSE)
> > > 
> > > 
> > > ### Hello @gitnyasha handshake
> > > ### Good job so far on creating your test cases, medal_sports you've used 'describe', 'it', and 'let' as it should ok_hand there is one more thing to add to them and also a couple of missing methods to work on construction_worker_man construction
> > > ## Project Specific
> > > #### Test cases are missing
> > > 
> > > * [ ]    All methods implemented in the Enumerable project are tested. let's add test cases for all of the methods existing in your enumerable.rb, you've missed these ones:
> > > * my_select
> > > * my_map
> > > * my_inject
> > > * multiply_els
> > > * sorted?
> > > * inj_param
> > > 
> > > #### cover positive and negative scenarios
> > > 
> > > * [ ]    add negative test cases (use not_to) to all your test cases for example:
> > > 
> > > ```
> > > .
> > > .
> > > let(:array) { [1, 2, 5, 8, 7, 98, 4] }
> > > .
> > > .
> > >   describe '#select' do
> > >     #Positive test case example
> > >     it 'Returns the filtered array if a block is given' do
> > >       expect(array.select { |element| element > 1}).to eql([2, 5, 8, 7, 98, 4])
> > >     end
> > >     #Negative test case example
> > >     it 'doesn\'t return the unfiltered array if a block is given' do
> > >       expect(array.select { |element| element > 1}).not_to eql(array)
> > >     end
> > >   end
> > > .
> > > .
> > > ```
> > > 
> > > 
> > > ### That's it! raised_hands
> > > ### Please pray do the changes man_technologist and submit back for a code review when you are done memo
> > > Happy coding! rocket
> > > Any questions? let me know on slack **@ Maru** woman_technologist
> > > PROJECT STATUS: REQUESTED CHANGES vertical_traffic_light
> > 
> > 
> > I thought the instructions was any of the 6 enumerables
> 
> * [ ]  It is stated in the additional Microverse requirements in the [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)
> 
> image

I have made the changes

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Very nice project!

It looks great and is nicely coming into place, but...

* [ ] still missing negative scenarios for some methods, for example, the wrong usage of a method.

Status: __Request changes__.

**Comment by gitnyasha** [comment]
> Very nice project!
> 
> It looks great and is nicely coming into place, but...
> 
> * [ ]  still missing negative scenarios for some methods, for example, the wrong usage of a method.
> 
> Status: **Request changes**.

which methods?

**Comment by gitnyasha** [comment]
> Very nice project!
> 
> It looks great and is nicely coming into place, but...
> 
> * [ ]  still missing negative scenarios for some methods, for example, the wrong usage of a method.
> 
> Status: **Request changes**.

which methods?

**Review by MauricioRobayo — APPROVED** [review]
@gitnyasha My mistake. I checked again and you are testing negative scenarios for all methods. Really sorry about that. Please accept my apologies. Will update the code review.

**Comment by gitnyasha** [comment]
> @gitnyasha My mistake. I checked again and you are testing negative scenarios for all methods. Really sorry about that. Please accept my apologies. Will update the code review.

still waiting for the update

**Comment by MauricioRobayo** [comment]
@gitnyasha It's going to take some time, probably by tomorrow it should be updated. I have already made the request to update it, but it is a manual process done by someone else. You can still move on, if it is not updated by tomorrow please remind me to recheck again.

**Pull request merged**
